In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
raw_data = pd.read_csv(
    "../data/raw/raw_data.csv"
)

hourly_data = pd.read_csv(
    "../data/raw/sequences_1h_data.csv"
)

print("Raw data shape:", raw_data.shape)
print("Hourly data shape:", hourly_data.shape)

Raw data shape: (429394, 10)
Hourly data shape: (23376, 164)

In [3]:
raw_data.head()

,interval_start,equipment_ID,alarm,type,start,end,elapsed,pi,po,speed
0,2020-01-01 11:21:28.907000+00:00,s_1,A_000,scheduled_downtime,1.577878e+09,1.577878e+09,63050,59916598,59517799,0
1,2020-01-01 11:22:31.957000+00:00,s_1,A_000,idle,1.577878e+09,1.577878e+09,30840,59916598,59517799,0
2,2020-01-01 11:23:02.797000+00:00,s_1,A_000,scheduled_downtime,1.577878e+09,1.577879e+09,1410671,59916598,59517799,0
3,2020-01-01 11:46:33.468000+00:00,s_1,A_000,idle,1.577879e+09,1.577881e+09,1524520,59916598,59517799,0
4,2020-01-01 12:11:57.988000+00:00,s_1,A_000,scheduled_downtime,1.577881e+09,1.577884e+09,2831270,59916598,59517799,0

In [4]:
hourly_data.head()

,interval_start,equipment_ID,count_sum,A_028,A_029,A_024,A_045,A_001,A_058,A_064,A_030,A_101,A_002,A_107,A_056,A_015,A_032,A_026,A_003,A_008,A_078,A_070,A_004,A_005,A_009,A_016,A_010,A_027,A_020,A_017,A_048,A_022,A_011,A_012,A_013,A_042,A_023,A_034,A_036,A_079,A_077,A_090,A_021,A_049,A_006,#changes,%idle,%production,%downtime,%performance_loss,%scheduled_downtime,idle/idle,idle/production,idle/downtime,idle/performance_loss,idle/scheduled_downtime,production/idle,production/production,production/downtime,production/performance_loss,production/scheduled_downtime,downtime/idle,downtime/production,downtime/downtime,downtime/performance_loss,downtime/scheduled_downtime,performance_loss/idle,performance_loss/production,performance_loss/downtime,performance_loss/performance_loss,performance_loss/scheduled_downtime,scheduled_downtime/idle,scheduled_downtime/production,scheduled_downtime/downtime,scheduled_downtime/performance_loss,scheduled_downtime/scheduled_downtime,A_043,A_051,A_106,A_050,A_018,A_102,A_031,A_103,A_083,A_081,A_074,A_071,A_073,A_104,A_084,A_105,A_116,A_128,A_109,A_132,A_062,A_131,A_035,A_040,A_039,A_055,A_127,A_007,A_108,A_037,A_119,A_115,A_125,A_124,A_130,A_052,A_129,A_019,A_126,A_110,A_123,A_114,A_120,A_121,A_098,A_095,A_087,A_111,A_117,A_044,A_122,A_085,A_057,A_066,A_112,A_118,A_113,A_093,A_041,A_076,A_088,A_097,A_065,A_091,A_067,A_068,A_033,A_082,A_075,A_099,A_086,A_100,A_096,A_094,A_089,A_092,A_038,A_080,A_069,A_072,A_047,A_059,A_046,A_063,A_053,A_054,A_060,A_061
0,2020-01-01 14:00:00,s_1,4,0.0,0,0,NaN,0.0,NaN,0.0,0.0,NaN,0,NaN,0,NaN,0.0,0.0,0,0,0.0,0.0,0,0,0,0,1,1,0,0,0.0,0.0,NaN,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,18.0,0.021523,0.861729,0.052261,0.020092,0.044395,1.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-01 15:00:00,s_1,2,0.0,0,0,NaN,0.0,NaN,0.0,0.0,NaN,0,NaN,0,NaN,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,5.0,0.000000,0.870897,0.117704,0.011399,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01 17:00:00,s_1,1,0.0,0,0,NaN,0.0,NaN,0.0,0.0,NaN,0,NaN,0,NaN,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,0.000000,0.978483,0.021517,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-01 18:00:00,s_1,4,0.0,0,0,NaN,0.0,NaN,0.0,0.0,NaN,0,NaN,0,NaN,0.0,0.0,0,0,0.0,0.0,0,3,0,0,0,0,0,0,0.0,0.0,NaN,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,8.0,0.000000,0.471066,0.468384,0.000000,0.060550,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-01 19:00:00,s_1,1,0.0,0,0,NaN,0.0,NaN,0.0,0.0,NaN,0,NaN,0,NaN,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,1,0,0,0.0,0.0,NaN,NaN,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,0.000000,0.987024,0.007778,0.005198,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print("RAW DATA COLUMNS")
print(raw_data.columns.tolist())

print("\nHOURLY DATA COLUMNS")
print(hourly_data.columns.tolist())

RAW DATA COLUMNS
['interval_start', 'equipment_ID', 'alarm', 'type', 'start', 'end', 'elapsed', 'pi', 'po', 'speed']

HOURLY DATA COLUMNS
['interval_start', 'equipment_ID', 'count_sum', 'A_028', 'A_029', 'A_024', 'A_045', 'A_001', 'A_058', 'A_064', 'A_030', 'A_101', 'A_002', 'A_107', 'A_056', 'A_015', 'A_032', 'A_026', 'A_003', 'A_008', 'A_078', 'A_070', 'A_004', 'A_005', 'A_009', 'A_016', 'A_010', 'A_027', 'A_020', 'A_017', 'A_048', 'A_022', 'A_011', 'A_012', 'A_013', 'A_042', 'A_023', 'A_034', 'A_036', 'A_079', 'A_077', 'A_090', 'A_021', 'A_049', 'A_006', '#changes', '%idle', '%production', '%downtime', '%performance_loss', '%scheduled_downtime', 'idle/idle', 'idle/production', 'idle/downtime', 'idle/performance_loss', 'idle/scheduled_downtime', 'production/idle', 'production/production', 'production/downtime', 'production/performance_loss', 'production/scheduled_downtime', 'downtime/idle', 'downtime/production', 'downtime/downtime', 'downtime/performance_loss', 'downtime/scheduled_downtime', 'performance_loss/idle', 'performance_loss/production', 'performance_loss/downtime', 'performance_loss/performance_loss', 'performance_loss/scheduled_downtime', 'scheduled_downtime/idle', 'scheduled_downtime/production', 'scheduled_downtime/downtime', 'scheduled_downtime/performance_loss', 'scheduled_downtime/scheduled_downtime', 'A_043', 'A_051', 'A_106', 'A_050', 'A_018', 'A_102', 'A_031', 'A_103', 'A_083', 'A_081', 'A_074', 'A_071', 'A_073', 'A_104', 'A_084', 'A_105', 'A_116', 'A_128', 'A_109', 'A_132', 'A_062', 'A_131', 'A_035', 'A_040', 'A_039', 'A_055', 'A_127', 'A_007', 'A_108', 'A_037', 'A_119', 'A_115', 'A_125', 'A_124', 'A_130', 'A_052', 'A_129', 'A_019', 'A_126', 'A_110', 'A_123', 'A_114', 'A_120', 'A_121', 'A_098', 'A_095', 'A_087', 'A_111', 'A_117', 'A_044', 'A_122', 'A_085', 'A_057', 'A_066', 'A_112', 'A_118', 'A_113', 'A_093', 'A_041', 'A_076', 'A_088', 'A_097', 'A_065', 'A_091', 'A_067', 'A_068', 'A_033', 'A_082', 'A_075', 'A_099', 'A_086', 'A_100', 'A_096', 'A_094', 'A_089', 'A_092', 'A_038', 'A_080', 'A_069', 'A_072', 'A_047', 'A_059', 'A_046', 'A_063', 'A_053', 'A_054', 'A_060', 'A_061']

In [6]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 429394 entries, 0 to 429393
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   interval_start  429394 non-null  str
 1   equipment_ID    429394 non-null  str
 2   alarm           429394 non-null  str
 3   type            429394 non-null  str
 4   start           429394 non-null  float64
 5   end             429394 non-null  float64
 6   elapsed         429394 non-null  int64
 7   pi              429394 non-null  int64
 8   po              429394 non-null  int64
 9   speed           429394 non-null  int64
dtypes: float64(2), int64(4), str(4)
memory usage: 53.6 MB

In [7]:
hourly_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 23376 entries, 0 to 23375
Columns: 164 entries, interval_start to A_061
dtypes: float64(143), int64(19), str(2)
memory usage: 29.7 MB

In [8]:
print("RAW DATA MISSING VALUES")
print(raw_data.isnull().sum())

RAW DATA MISSING VALUES
interval_start    0
equipment_ID      0
alarm             0
type              0
start             0
end               0
elapsed           0
pi                0
po                0
speed             0
dtype: int64

In [9]:
print("HOURLY DATA MISSING VALUES")
print(hourly_data.isnull().sum())

HOURLY DATA MISSING VALUES
interval_start        0
equipment_ID          0
count_sum             0
A_028              4743
A_029                 0
                  ...
A_063             19417
A_053             19417
A_054             19417
A_060             19417
A_061             19417
Length: 164, dtype: int64

In [10]:
print(
    "Raw duplicates:",
    raw_data.duplicated().sum()
)

print(
    "Hourly duplicates:",
    hourly_data.duplicated().sum()
)

Raw duplicates: 0
Hourly duplicates: 0

In [11]:
print(
    raw_data["equipment_ID"].unique()
)

print(
    "Number of machines:",
    raw_data["equipment_ID"].nunique()
)

<ArrowStringArray>
['s_1', 's_2', 's_3', 's_4', 's_5']
Length: 5, dtype: str
Number of machines: 5

In [12]:
raw_data["equipment_ID"].value_counts()

equipment_ID
s_1    127676
s_5    100855
s_4     96644
s_2     69765
s_3     34454
Name: count, dtype: int64

In [13]:
raw_data["alarm"].value_counts().head(20)

alarm
A_000    337310
A_065     18879
A_101     18416
A_005     12226
A_010      9278
A_020      5100
A_001      4403
A_006      3943
A_066      3384
A_003      2225
A_017      1763
A_012      1162
A_011      1150
A_016      1142
A_002       842
A_067       834
A_004       705
A_068       646
A_008       514
A_070       343
Name: count, dtype: int64

In [14]:
raw_data["type"].value_counts()

type
production            146795
performance_loss      118584
downtime               92084
idle                   50149
scheduled_downtime     21782
Name: count, dtype: int64

In [15]:
raw_data.describe(include="all")

,interval_start,equipment_ID,alarm,type,start,end,elapsed,pi,po,speed
count,429394,429394,429394,429394,4.293940e+05,4.293940e+05,4.293940e+05,4.293940e+05,4.293940e+05,429394.000000
unique,429389,5,133,5,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-09-21 22:00:00+00:00,s_1,A_000,production,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,127676,337310,146795,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1.613331e+09,1.613331e+09,3.699865e+05,3.119454e+07,3.460735e+07,5097.274184
std,NaN,NaN,NaN,NaN,1.930947e+07,1.930949e+07,1.368095e+06,3.432799e+07,3.410896e+07,1403.143281
min,NaN,NaN,NaN,NaN,1.577837e+09,1.577837e+09,1.140000e+02,0.000000e+00,0.000000e+00,0.000000
25%,NaN,NaN,NaN,NaN,1.595056e+09,1.595057e+09,1.392000e+04,8.433338e+05,1.031434e+06,4500.000000
50%,NaN,NaN,NaN,NaN,1.619039e+09,1.619039e+09,6.429400e+04,1.123067e+07,2.600625e+07,5526.000000
75%,NaN,NaN,NaN,NaN,1.629970e+09,1.629970e+09,2.402800e+05,6.622470e+07,6.579510e+07,6176.000000
max,NaN,NaN,NaN,NaN,1.641080e+09,1.641084e+09,7.929008e+07,3.385590e+08,3.391488e+08,6500.000000

In [16]:
hourly_data.describe(include="all")

,interval_start,equipment_ID,count_sum,A_028,A_029,A_024,A_045,A_001,A_058,A_064,A_030,A_101,A_002,A_107,A_056,A_015,A_032,A_026,A_003,A_008,A_078,A_070,A_004,A_005,A_009,A_016,A_010,A_027,A_020,A_017,A_048,A_022,A_011,A_012,A_013,A_042,A_023,A_034,A_036,A_079,A_077,A_090,A_021,A_049,A_006,#changes,%idle,%production,%downtime,%performance_loss,%scheduled_downtime,idle/idle,idle/production,idle/downtime,idle/performance_loss,idle/scheduled_downtime,production/idle,production/production,production/downtime,production/performance_loss,production/scheduled_downtime,downtime/idle,downtime/production,downtime/downtime,downtime/performance_loss,downtime/scheduled_downtime,performance_loss/idle,performance_loss/production,performance_loss/downtime,performance_loss/performance_loss,performance_loss/scheduled_downtime,scheduled_downtime/idle,scheduled_downtime/production,scheduled_downtime/downtime,scheduled_downtime/performance_loss,scheduled_downtime/scheduled_downtime,A_043,A_051,A_106,A_050,A_018,A_102,A_031,A_103,A_083,A_081,A_074,A_071,A_073,A_104,A_084,A_105,A_116,A_128,A_109,A_132,A_062,A_131,A_035,A_040,A_039,A_055,A_127,A_007,A_108,A_037,A_119,A_115,A_125,A_124,A_130,A_052,A_129,A_019,A_126,A_110,A_123,A_114,A_120,A_121,A_098,A_095,A_087,A_111,A_117,A_044,A_122,A_085,A_057,A_066,A_112,A_118,A_113,A_093,A_041,A_076,A_088,A_097,A_065,A_091,A_067,A_068,A_033,A_082,A_075,A_099,A_086,A_100,A_096,A_094,A_089,A_092,A_038,A_080,A_069,A_072,A_047,A_059,A_046,A_063,A_053,A_054,A_060,A_061
count,23376,23376,23376.000000,18633.000000,23376.000000,23376.000000,14403.000000,18633.000000,9660.000000,11949.000000,20651.000000,10444.000000,23376.00000,2976.000000,23376.000000,11678.000000,18633.000000,18633.000000,23376.000000,23376.000000,14674.000000,14674.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,20651.000000,18633.000000,14403.000000,14403.000000,23376.000000,23376.000000,23376.000000,18633.000000,15908.000000,16692.000000,14674.000000,11949.000000,23376.000000,20651.000000,18633.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.000000,23376.0,23376.000000,23376.000000,23376.0,23376.000000,23376.0,23376.0,23376.000000,23376.0,23376.0,23376.0,23376.000000,23376.000000,23376.000000,23376.000000,23376.0,23376.0,23376.000000,23376.0,23376.000000,20400.000000,11427.000000,2725.000000,6684.000000,20400.000000,2725.000000,15657.000000,2725.000000,16441.000000,16441.000000,16441.000000,16441.000000,16441.000000,7468.000000,16441.000000,7468.000000,4743.000000,4743.000000,4743.000000,4743.000000,17675.000000,4743.000000,17675.000000,8702.000000,8702.000000,8702.000000,4743.000000,8702.000000,4743.000000,17675.000000,4743.000000,4743.000000,4743.000000,4743.000000,4743.000000,17675.000000,4743.000000,8702.000000,4743.000000,4743.000000,4743.000000,4743.000000,4743.000000,4743.000000,13716.000000,13716.000000,13716.000000,4743.000000,4743.000000,17675.000000,4743.000000,13716.000000,8702.000000,13716.000000,4743.000000,4743.000000,4743.000000,8973.000000,12932.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,12932.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,8973.000000,12932.000000,8973.000000,8973.000000,8973.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000,3959.000000
unique,13732,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-04-27 11:00:00,s_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,5,8973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,3.929629,0.013524,0.003380,0.004406,0.004444,0.236301,0.001553,0.017658,0.003874,1.763309,0.03602,0.000336,0.001454,0.000599,0.007353,0.003703,0.095183,0.021988,0.001567,0.023375,0.030159,0.523015,0.012962,0.048854,0.396903,0.013261,0.218172,0.075419,0.001162,0.005742,0.079844,0.080678,0.008855,0.004962,0.006117,0.004454,0.002640,0.001618,0.001090,0.000502,0.006117,0.001065,0.211614,14.316735,0.068730,0.631779,0.132762,0.131189,0.035539,0.760096,0.007315,0.001882,0.452515,0.003422,0.0,4.801805,0.724119,0.0,0.259283,0.0,0.0,2.939254,0.0,0.0,0.0,0.830424,0.002310,3.145320,0.002267,0.0,0.0,0.264973,0.0,0.121749,0.009951,0.003325,0.000367,0.001197,0.001029,0.032661,0.009133,0.000734,0.013442,0.000852,0.007785,0.013685,0.005292,0.003214,0.004014,0.001741,0.008012,0.005903,0.003163,0.000211,0.001018,0.000211,0.007581,0.007355,0.002068,0.003103,0.000211,0.002643,0.014337,0.000396,0.001054,0.003373,0.001476,0.000633,0.000633,0.000226,0.000211,0.000230,0.001476,0.000211,0.000422,0.002530,0.000422,0.001476,0.000437,0.002479,0.003281,0.001265,0.000843,0.000622,0.001054,0.000510,0.002068,0.246719,0.005271,0.001476,0.004638,0.000223,0.000773,0.005126,0.000780,0.001226,2.103979,0.001003,0.092946,0.071994,0.001005,0.001337,0.000111,0.000334,0.002452,0.000557,0.001226,0.001449,0.000223,0.001895,0.001005,0.000111,0.006129,0.000780,0.000253,0.000505,0.000758,0.001516,0.004041,0.000505,0.000253,0.000253
std,NaN,NaN,3.644369,0.115972,0.066937,0.098881,0.067550,0.514212,0.048773,0.134230,0.067358,2.393512,0.20618,0.018331,0.040293,0.027756,0.121708,0.064179,0.614868,0.219742,0.126544,0.430471,0.192005,1.886645,0.119370,0.243698,1.520618,0.133707,0.834018,0.447741,0.036805,0.098939,0.317321,0.325964,0.112372,0.106158,0.103443,0.089315,0.126336,0.043066,0.040429,0.022404,0.083282,0.035468,0.568919,12.433900,0.160961,0.279628,0.162798,0.169048,0.103837,1.908793,0.085217,0.043345,0.497751,0.058402,0.0,4.855353,0.446967,0.0,0.438251,0.0,0.0,3.646038,0.0,0.0,0.0,0.375268,0.048009,4.347117,0.047563,0.0,0.0,0.441328,0.0,0.580153,0.153234,0.099831,0.019157,0.066989,0.042576,0.262774,0.140646,0.027086,0.256785,0.029169,0.114359,0.150004,0.075833,0.058921,0.067873,0.066456,0.102371,0.110437,0.056154,0.014520,0.042539,0.014520,0.118691,0.129327,0.052479,0.105539,0.014520,0.053537,0.118888,0.019897,0.038406,0.073970,0.038393,0.025144,0.043561,0.015042,0.014520,0.015159,0.038393,0.014520,0.029040,0.058032,0.020533,0.056223,0.020911,0.060328,0.074857,0.035548,0.029031,0.024940,0.038406,0.037217,0.062477,1.055966,0.085750,0.043540,0.096215,0.014929,0.030453,0.172755,0.038057,0.038045,2.559719,0.031656,0.343801,0.287093,0.031691,0.051703,0.010557,0.018283,0.051662,0.031667,0.064206,0.065915,0.014929,0.050596,0.040286,0.010557,0.161725,0.031662,0.015893,0.022473,0.047679,0.038905,0.067316,0.022473,0.015893,0.015893
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000438,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.456896,0.029329,0.005837,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.702421,0.078096,0.067561,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,4.000000,1.000000,0.0,0.000000,0.0,0.0,2.000000,0.0,0.0,0.0,1.000000,0.000000,2.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,0.049836,0.857945,0.171148,0.184372,0.014923,1.000000,0.000000,0.000000,1.000000,0.000000,0.0,7.000000,1.000000,0.0,1.000000,0.0,0.0,4.000000,0.0,0.0,0.0,1.000000,0.000000,4.000000,0.000000,0.0,0.0,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,NaN,74.000000,2.000000,5.000000,7.000000,2.000000,6.000000,3.000000,3.000000,3.000000,31.000000,4.00000,1.000000,2.000000,2.000000,6.000000,2.000000,17.000000,9.000000,15.000000,31.000000,4.000000,45.000000,3.000000,4.000000,72.000000,4.000000,18.000000,21.000000,2.000000,4.000000,4.000000,5.000000,3.000000,6.000000,6.000000,6.000000,14.000000,2.000000,2.000000,1.000000,2.000000,2.000000,8.000000,197.000000,0.996116,0.999512,1.000000,0.992402,0.986039,29.000000,1.000000,1.000000,1.000000,1.000000,0.0,92.000000,1.000000,0.0,1.000000,0.0,0.0,73.000000,0.0,0.0,0.0,1.000000,1.000000,58.000000,1.000000,0.0,0.0,1.000000,0.0,21.000000,9.000000,6.000000,1.000000,5.000000,3.000000,4.000000,6.000000,1.000000,10.000000,1.000000,6.000000,8.000000,2.000000,2.000000,3.000000,4.000000,3.000000,5.000000,1.000000,1.000000,3.000000,1.000000,6.000000,4.000000,2.000000,6.000000,1.000000,2.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,3.000000,1.000000,3.000000,4.000000,1.000000,1.000000,1.000000,2.000000,4.000000,4.000000,24.000000,2.000000,2.000000,3.000000,1.000000,2.000000,13.000000,2.000000,2.000000,26.000000,1.000000,7.000000,6.000000,1.000000,3.000000,1.000000,1.000000,2.000000,2.000000,5.000000,4.000000,1.000000,2.000000,3.000000,1.000000,8.000000,2.000000,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000

In [17]:
raw_data["interval_start"] = pd.to_datetime(
    raw_data["interval_start"],
    errors="coerce"
)

print(raw_data["interval_start"].min())
print(raw_data["interval_start"].max())

2020-01-01 00:05:02.863000+00:00
2022-01-01 23:41:35.677000+00:00